--  Creation du Stage pour stocker les fichiers .wav de Kaggle
CREATE STAGE IF NOT EXISTS STG_RESPIRATORY_SOUNDS
DIRECTORY = (ENABLE = TRUE);

--  Table pour les metadonnees des patients et diagnostics
CREATE TABLE IF NOT EXISTS RAW_RESPIRATORY_METADATA (
    FILE_NAME STRING,
    DIAGNOSIS STRING,        
    DURATION_SECONDS FLOAT,
    SAMPLE_RATE INT,
    UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--  Vue pour simplifier l'acces aux fichiers du stage
CREATE OR REPLACE VIEW V_SOUND_FILES AS
SELECT * FROM DIRECTORY(@STG_RESPIRATORY_SOUNDS);