name: Test Snowflake Connection (Python)

on:
  push:
    branches: [ exploration_devops ]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Snowflake Connector
        run: |
          pip install snowflake-connector-python

      - name: Execute Test Script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: COMPUTE_WH # Vérifie que ce nom est correct dans ton Snowflake
        run: |
          python scripts/deploy_sql.py